<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:tns="http://core.nip.nibss/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" name="NIPTSQInterface" targetNamespace="http://core.nip.nibss/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="http://192.234.10.233:88/NIPWS/NIPTSQInterface?xsd=1" namespace="http://core.nip.nibss/" />
    </xsd:schema>
  </types>
  <message name="txnstatusquerysingleitem">
    <part name="parameters" element="tns:txnstatusquerysingleitem" />
  </message>
  <message name="txnstatusquerysingleitemResponse">
    <part name="parameters" element="tns:txnstatusquerysingleitemResponse" />
  </message>
  <portType name="NIPTSQInterface">
    <operation name="txnstatusquerysingleitem">
      <input wsam:Action="http://core.nip.nibss/NIPTSQInterface/txnstatusquerysingleitemRequest" message="tns:txnstatusquerysingleitem" />
      <output wsam:Action="http://core.nip.nibss/NIPTSQInterface/txnstatusquerysingleitemResponse" message="tns:txnstatusquerysingleitemResponse" />
    </operation>
  </portType>
  <binding name="NIPTQSInterfacePortBinding" type="tns:NIPTSQInterface">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="txnstatusquerysingleitem">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  <service name="NIPTSQInterface">
    <port name="NIPTQSInterfacePort" binding="tns:NIPTQSInterfacePortBinding">
      <soap:address location="http://192.234.10.233:88/NIPWS/NIPTSQInterface" />
    </port>
  </service>
</definitions>