//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulktraImalJob.EWSService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EWSService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchExistingCustomerByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchExistingCustomerByName(string lastname, string firstname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchExistingCustomerByCorporate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchExistingCustomerByCorporate(string fullname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNuban", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getNuban(string bracode, string cusnum, string curcode, string ledcode, string subacctcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowCustomerDetailsByPartyID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ShowCustomerDetailsByPartyID(string partyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveVisaRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveVisaRequest(
                    string nuban, 
                    string telephone, 
                    string gsm, 
                    string email, 
                    string namePrefix, 
                    string gender, 
                    string passportNum, 
                    string passportIssuedate, 
                    string passportExpirydate, 
                    string passportPlaceofIssue, 
                    string secretQuestion, 
                    string secretAnswer, 
                    int resident, 
                    int countryResident, 
                    int billingCountry, 
                    int billingRegion, 
                    int billingCityofReg, 
                    string billingAddress, 
                    int homeCountry, 
                    int homeRegion, 
                    int homeCity, 
                    string homeAddress, 
                    string addedBy, 
                    string cardFirstName, 
                    string cardSurname, 
                    string dob, 
                    string carddeliveryverve, 
                    string pinDeliveryVerve);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveChequeBookRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveChequeBookRequest(string nuban, int booklets, int statec, int branchCode, string branchName, int deliveryBranchCode, string chequeName, int chequeSN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsVerveCardExisting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IsVerveCardExisting(string cusNum, string ledCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsVerveCardExistingNuban", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IsVerveCardExistingNuban(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChequeTemplateNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetChequeTemplateNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChequeStateCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetChequeStateCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BasicOpening", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BasicOpening(string FirstName, string LastName, string OtherName, string Gender, string Mobile, string Email, string Title, string HomeAddress, string HomeState, string BirthDate, string DocumentReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBranches", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBranches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMS(string message, string gsm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveInstantCardRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveInstantCardRequest(string nuban, string city, string region, string cardDeliveryBranch, string pinDeliveryBranch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveVerveCardRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveVerveCardRequest(string nuban, string city, string region, string cardDeliveryBranch, string pinDeliveryBranch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsPNDExisting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IsPNDExisting(string braCode, string cusNum, string curCode, string ledCode, string subAcctCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsPNDExistingByNuban", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IsPNDExistingByNuban(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsKYCComplete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IsKYCComplete(string braCode, string cusNum, string curCode, string ledCode, string subAcctCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsKYCCompleteByNuban", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IsKYCCompleteByNuban(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKYCStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetKYCStatus(string braCode, string cusNum, string curCode, string ledCode, string subAcctCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKYCStatusNuban", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetKYCStatusNuban(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKYCDetailsByNuban", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetKYCDetailsByNuban(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKYCDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetKYCDetails(string braCode, string cusNum, string curCode, string ledCode, string subAcctCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHumanManagerData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetHumanManagerData(string staffNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetADDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetADDetails(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneratePartyID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GeneratePartyID(string bracode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBankCustByCus_Nums", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBankCustByCus_Nums(string cusNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIMALCustByCIF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetIMALCustByCIF(int cif_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBankCusNum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBankCusNum(string cusNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutPND", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PutPND(string BRA_CODE, string CUS_NUM, string CUR_CODE, string LED_CODE, string SUB_ACCT_CODE, string TELL_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBranchCodeForUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBranchCodeForUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTellerForUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTellerForUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTSSAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateTSSAccount(string braCode, string cusNum, string curCode, string ledCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewAccountForExistingCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateNewAccountForExistingCustomer(string BRA_CODE, string CUS_NUM, string NEW_BRA_CODE, string NEW_CUR_CODE, string LED_CODE, string ACCT_NAT, string TELL_USERNAME, string APPLY_PND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewAccountForExistingCustomerPos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateNewAccountForExistingCustomerPos(string BRA_CODE, string CUS_NUM, string NEW_BRA_CODE, string NEW_CUR_CODE, string LED_CODE, string ACCT_NAT, string TELL_USERNAME, string APPLY_PND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewAccountForExistingCustomerNuban", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateNewAccountForExistingCustomerNuban(string nuban, string NEW_BRA_CODE, string NEW_CUR_CODE, string LED_CODE, string ACCT_NAT, string TELL_USERNAME, string APPLY_PND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewCustomerAndAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateNewCustomerAndAccount(
                    string TELL_USERNAME, 
                    string ADDRESS_LINE1, 
                    string ADDRESS_LINE2, 
                    string BIR_DATE_STR, 
                    string BRA_CODE, 
                    string ADDRESS_STATE_CODE, 
                    string COUNTRY_OF_RESIDENCE_CODE, 
                    string CUSTOMER_CLASSIFICATION_CODE, 
                    string CUSTOMER_NAME, 
                    string EMAIL, 
                    string GENDER, 
                    string CUR_CODE, 
                    string LED_CODE, 
                    string ACCT_NAT, 
                    string MOB_NUM, 
                    string FNAME, 
                    string MNAME, 
                    string LNAME, 
                    string NATIONALITY_CODE, 
                    string OLD_CUSTOMER_NUMBER, 
                    string LGA_OF_ORIGIN_CODE, 
                    string REG_NUM, 
                    string SOCIAL_SECURITY_NUM, 
                    string STATE_ORIGIN_CODE, 
                    string TITLE_CODE, 
                    string TOWN, 
                    string APPLY_PND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBranch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getBranch();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBVN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBVN(string bvn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLedger", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLedger();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTitle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTitle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTitleName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTitleName(string titleCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStateName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetStateName(string stateCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCountry();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNationality", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetNationality();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStateOfOrigin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetStateOfOrigin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAccountCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLgaOrigin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLgaOrigin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerClassification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCustomerClassification();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountNature", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAccountNature();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountDetailsByNuban", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAccountDetailsByNuban(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertNubanToBanksFormat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConvertNubanToBanksFormat(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAccountDetails(string braCode, string cusNum, string curCode, string ledCode, string subAcctCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountDetails2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAccountDetails2(string braCode, string cusNum, string curCode, string ledCode, string subAcctCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsTellerIDExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsTellerIDExists(string tellerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRegionalChannelCoordinatorUsernameForBranchCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getRegionalChannelCoordinatorUsernameForBranchCode(string bracode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isRegionalChannelCoordinatorForBranchCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string isRegionalChannelCoordinatorForBranchCode(string username, string bracode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendMail(string destinationEmail, string sourceEmail, string body, string subject);
        
        // CODEGEN: Parameter 'attachmentData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMailWithAttachment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BulktraImalJob.EWSService.SendMailWithAttachmentResponse SendMailWithAttachment(BulktraImalJob.EWSService.SendMailWithAttachmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsTellerIDPasswordActive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsTellerIDPasswordActive(string tellerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAdDetailsByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAdDetailsByID(string StaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Numbergenerate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Numbergenerate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHighestRankedStaff", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHighestRankedStaff(string[] staffusernames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStaffGrade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAllStaffGrade(string staffId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffGradeWithStaffID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetStaffGradeWithStaffID(string staffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIMALCustByAcctNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetIMALCustByAcctNo(string cif_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIMALCustByMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetIMALCustByMobile(string mobile_234_format, string mobile_080_format);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBankCustByNuban", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBankCustByNuban(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountsByMobileNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAccountsByMobileNo(string mobileNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBankCustByMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBankCustByMobile(string mobile_234_format, string mobile_080_format);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBankName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBankName(string bankCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBankBVN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBankBVN(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIMALBVN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetIMALBVN(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckNUBANForComplaint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CheckNUBANForComplaint(string NUBAN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountFullinfoAllForComplaint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAccountFullinfoAllForComplaint(string NUBAN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckAcct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CheckAcct(string AccNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getClientsForIMAL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getClientsForIMAL(string rrr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckNUBANOmImal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CheckNUBANOmImal(string NUBAN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getcurrec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getcurrec(string cc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAcctTypeFromBank", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAcctTypeFromBank(string bra_code, string cus_num, string cur_code, string led_code, string sub_led_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWorkflowTrackerExceptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetWorkflowTrackerExceptions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsUserOnLeave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IsUserOnLeave(string username);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMailWithAttachment", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMailWithAttachmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string destinationEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sourceEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string ccEmailSeparatedByComma;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] attachmentData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string attachmentFilename;
        
        public SendMailWithAttachmentRequest() {
        }
        
        public SendMailWithAttachmentRequest(string destinationEmail, string sourceEmail, string body, string subject, string ccEmailSeparatedByComma, byte[] attachmentData, string attachmentFilename) {
            this.destinationEmail = destinationEmail;
            this.sourceEmail = sourceEmail;
            this.body = body;
            this.subject = subject;
            this.ccEmailSeparatedByComma = ccEmailSeparatedByComma;
            this.attachmentData = attachmentData;
            this.attachmentFilename = attachmentFilename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMailWithAttachmentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMailWithAttachmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendMailWithAttachmentResult;
        
        public SendMailWithAttachmentResponse() {
        }
        
        public SendMailWithAttachmentResponse(string SendMailWithAttachmentResult) {
            this.SendMailWithAttachmentResult = SendMailWithAttachmentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BulktraImalJob.EWSService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BulktraImalJob.EWSService.ServiceSoap>, BulktraImalJob.EWSService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SearchExistingCustomerByName(string lastname, string firstname) {
            return base.Channel.SearchExistingCustomerByName(lastname, firstname);
        }
        
        public System.Data.DataSet SearchExistingCustomerByCorporate(string fullname) {
            return base.Channel.SearchExistingCustomerByCorporate(fullname);
        }
        
        public string getNuban(string bracode, string cusnum, string curcode, string ledcode, string subacctcode) {
            return base.Channel.getNuban(bracode, cusnum, curcode, ledcode, subacctcode);
        }
        
        public string ShowCustomerDetailsByPartyID(string partyID) {
            return base.Channel.ShowCustomerDetailsByPartyID(partyID);
        }
        
        public string SaveVisaRequest(
                    string nuban, 
                    string telephone, 
                    string gsm, 
                    string email, 
                    string namePrefix, 
                    string gender, 
                    string passportNum, 
                    string passportIssuedate, 
                    string passportExpirydate, 
                    string passportPlaceofIssue, 
                    string secretQuestion, 
                    string secretAnswer, 
                    int resident, 
                    int countryResident, 
                    int billingCountry, 
                    int billingRegion, 
                    int billingCityofReg, 
                    string billingAddress, 
                    int homeCountry, 
                    int homeRegion, 
                    int homeCity, 
                    string homeAddress, 
                    string addedBy, 
                    string cardFirstName, 
                    string cardSurname, 
                    string dob, 
                    string carddeliveryverve, 
                    string pinDeliveryVerve) {
            return base.Channel.SaveVisaRequest(nuban, telephone, gsm, email, namePrefix, gender, passportNum, passportIssuedate, passportExpirydate, passportPlaceofIssue, secretQuestion, secretAnswer, resident, countryResident, billingCountry, billingRegion, billingCityofReg, billingAddress, homeCountry, homeRegion, homeCity, homeAddress, addedBy, cardFirstName, cardSurname, dob, carddeliveryverve, pinDeliveryVerve);
        }
        
        public string SaveChequeBookRequest(string nuban, int booklets, int statec, int branchCode, string branchName, int deliveryBranchCode, string chequeName, int chequeSN) {
            return base.Channel.SaveChequeBookRequest(nuban, booklets, statec, branchCode, branchName, deliveryBranchCode, chequeName, chequeSN);
        }
        
        public string IsVerveCardExisting(string cusNum, string ledCode) {
            return base.Channel.IsVerveCardExisting(cusNum, ledCode);
        }
        
        public string IsVerveCardExistingNuban(string nuban) {
            return base.Channel.IsVerveCardExistingNuban(nuban);
        }
        
        public System.Data.DataSet GetChequeTemplateNames() {
            return base.Channel.GetChequeTemplateNames();
        }
        
        public System.Data.DataSet GetChequeStateCodes() {
            return base.Channel.GetChequeStateCodes();
        }
        
        public string BasicOpening(string FirstName, string LastName, string OtherName, string Gender, string Mobile, string Email, string Title, string HomeAddress, string HomeState, string BirthDate, string DocumentReference) {
            return base.Channel.BasicOpening(FirstName, LastName, OtherName, Gender, Mobile, Email, Title, HomeAddress, HomeState, BirthDate, DocumentReference);
        }
        
        public System.Data.DataSet GetBranches() {
            return base.Channel.GetBranches();
        }
        
        public string SendSMS(string message, string gsm) {
            return base.Channel.SendSMS(message, gsm);
        }
        
        public string SaveInstantCardRequest(string nuban, string city, string region, string cardDeliveryBranch, string pinDeliveryBranch) {
            return base.Channel.SaveInstantCardRequest(nuban, city, region, cardDeliveryBranch, pinDeliveryBranch);
        }
        
        public string SaveVerveCardRequest(string nuban, string city, string region, string cardDeliveryBranch, string pinDeliveryBranch) {
            return base.Channel.SaveVerveCardRequest(nuban, city, region, cardDeliveryBranch, pinDeliveryBranch);
        }
        
        public string IsPNDExisting(string braCode, string cusNum, string curCode, string ledCode, string subAcctCode) {
            return base.Channel.IsPNDExisting(braCode, cusNum, curCode, ledCode, subAcctCode);
        }
        
        public string IsPNDExistingByNuban(string nuban) {
            return base.Channel.IsPNDExistingByNuban(nuban);
        }
        
        public string IsKYCComplete(string braCode, string cusNum, string curCode, string ledCode, string subAcctCode) {
            return base.Channel.IsKYCComplete(braCode, cusNum, curCode, ledCode, subAcctCode);
        }
        
        public string IsKYCCompleteByNuban(string nuban) {
            return base.Channel.IsKYCCompleteByNuban(nuban);
        }
        
        public string GetKYCStatus(string braCode, string cusNum, string curCode, string ledCode, string subAcctCode) {
            return base.Channel.GetKYCStatus(braCode, cusNum, curCode, ledCode, subAcctCode);
        }
        
        public string GetKYCStatusNuban(string nuban) {
            return base.Channel.GetKYCStatusNuban(nuban);
        }
        
        public System.Data.DataSet GetKYCDetailsByNuban(string nuban) {
            return base.Channel.GetKYCDetailsByNuban(nuban);
        }
        
        public System.Data.DataSet GetKYCDetails(string braCode, string cusNum, string curCode, string ledCode, string subAcctCode) {
            return base.Channel.GetKYCDetails(braCode, cusNum, curCode, ledCode, subAcctCode);
        }
        
        public System.Data.DataSet GetHumanManagerData(string staffNumber) {
            return base.Channel.GetHumanManagerData(staffNumber);
        }
        
        public System.Data.DataSet GetADDetails(string username) {
            return base.Channel.GetADDetails(username);
        }
        
        public string GeneratePartyID(string bracode) {
            return base.Channel.GeneratePartyID(bracode);
        }
        
        public System.Data.DataSet GetBankCustByCus_Nums(string cusNum) {
            return base.Channel.GetBankCustByCus_Nums(cusNum);
        }
        
        public System.Data.DataSet GetIMALCustByCIF(int cif_no) {
            return base.Channel.GetIMALCustByCIF(cif_no);
        }
        
        public System.Data.DataSet GetBankCusNum(string cusNum) {
            return base.Channel.GetBankCusNum(cusNum);
        }
        
        public string PutPND(string BRA_CODE, string CUS_NUM, string CUR_CODE, string LED_CODE, string SUB_ACCT_CODE, string TELL_ID) {
            return base.Channel.PutPND(BRA_CODE, CUS_NUM, CUR_CODE, LED_CODE, SUB_ACCT_CODE, TELL_ID);
        }
        
        public string GetBranchCodeForUser(string username) {
            return base.Channel.GetBranchCodeForUser(username);
        }
        
        public string GetTellerForUser(string username) {
            return base.Channel.GetTellerForUser(username);
        }
        
        public string CreateTSSAccount(string braCode, string cusNum, string curCode, string ledCode) {
            return base.Channel.CreateTSSAccount(braCode, cusNum, curCode, ledCode);
        }
        
        public string CreateNewAccountForExistingCustomer(string BRA_CODE, string CUS_NUM, string NEW_BRA_CODE, string NEW_CUR_CODE, string LED_CODE, string ACCT_NAT, string TELL_USERNAME, string APPLY_PND) {
            return base.Channel.CreateNewAccountForExistingCustomer(BRA_CODE, CUS_NUM, NEW_BRA_CODE, NEW_CUR_CODE, LED_CODE, ACCT_NAT, TELL_USERNAME, APPLY_PND);
        }
        
        public string CreateNewAccountForExistingCustomerPos(string BRA_CODE, string CUS_NUM, string NEW_BRA_CODE, string NEW_CUR_CODE, string LED_CODE, string ACCT_NAT, string TELL_USERNAME, string APPLY_PND) {
            return base.Channel.CreateNewAccountForExistingCustomerPos(BRA_CODE, CUS_NUM, NEW_BRA_CODE, NEW_CUR_CODE, LED_CODE, ACCT_NAT, TELL_USERNAME, APPLY_PND);
        }
        
        public string CreateNewAccountForExistingCustomerNuban(string nuban, string NEW_BRA_CODE, string NEW_CUR_CODE, string LED_CODE, string ACCT_NAT, string TELL_USERNAME, string APPLY_PND) {
            return base.Channel.CreateNewAccountForExistingCustomerNuban(nuban, NEW_BRA_CODE, NEW_CUR_CODE, LED_CODE, ACCT_NAT, TELL_USERNAME, APPLY_PND);
        }
        
        public string CreateNewCustomerAndAccount(
                    string TELL_USERNAME, 
                    string ADDRESS_LINE1, 
                    string ADDRESS_LINE2, 
                    string BIR_DATE_STR, 
                    string BRA_CODE, 
                    string ADDRESS_STATE_CODE, 
                    string COUNTRY_OF_RESIDENCE_CODE, 
                    string CUSTOMER_CLASSIFICATION_CODE, 
                    string CUSTOMER_NAME, 
                    string EMAIL, 
                    string GENDER, 
                    string CUR_CODE, 
                    string LED_CODE, 
                    string ACCT_NAT, 
                    string MOB_NUM, 
                    string FNAME, 
                    string MNAME, 
                    string LNAME, 
                    string NATIONALITY_CODE, 
                    string OLD_CUSTOMER_NUMBER, 
                    string LGA_OF_ORIGIN_CODE, 
                    string REG_NUM, 
                    string SOCIAL_SECURITY_NUM, 
                    string STATE_ORIGIN_CODE, 
                    string TITLE_CODE, 
                    string TOWN, 
                    string APPLY_PND) {
            return base.Channel.CreateNewCustomerAndAccount(TELL_USERNAME, ADDRESS_LINE1, ADDRESS_LINE2, BIR_DATE_STR, BRA_CODE, ADDRESS_STATE_CODE, COUNTRY_OF_RESIDENCE_CODE, CUSTOMER_CLASSIFICATION_CODE, CUSTOMER_NAME, EMAIL, GENDER, CUR_CODE, LED_CODE, ACCT_NAT, MOB_NUM, FNAME, MNAME, LNAME, NATIONALITY_CODE, OLD_CUSTOMER_NUMBER, LGA_OF_ORIGIN_CODE, REG_NUM, SOCIAL_SECURITY_NUM, STATE_ORIGIN_CODE, TITLE_CODE, TOWN, APPLY_PND);
        }
        
        public System.Data.DataSet getBranch() {
            return base.Channel.getBranch();
        }
        
        public System.Data.DataSet GetBVN(string bvn) {
            return base.Channel.GetBVN(bvn);
        }
        
        public System.Data.DataSet GetLedger() {
            return base.Channel.GetLedger();
        }
        
        public System.Data.DataSet GetTitle() {
            return base.Channel.GetTitle();
        }
        
        public string GetTitleName(string titleCode) {
            return base.Channel.GetTitleName(titleCode);
        }
        
        public System.Data.DataSet GetState() {
            return base.Channel.GetState();
        }
        
        public string GetStateName(string stateCode) {
            return base.Channel.GetStateName(stateCode);
        }
        
        public System.Data.DataSet GetCountry() {
            return base.Channel.GetCountry();
        }
        
        public System.Data.DataSet GetNationality() {
            return base.Channel.GetNationality();
        }
        
        public System.Data.DataSet GetStateOfOrigin() {
            return base.Channel.GetStateOfOrigin();
        }
        
        public System.Data.DataSet GetAccountCategory() {
            return base.Channel.GetAccountCategory();
        }
        
        public System.Data.DataSet GetLgaOrigin() {
            return base.Channel.GetLgaOrigin();
        }
        
        public System.Data.DataSet GetCustomerClassification() {
            return base.Channel.GetCustomerClassification();
        }
        
        public System.Data.DataSet GetAccountNature() {
            return base.Channel.GetAccountNature();
        }
        
        public System.Data.DataSet GetAccountDetailsByNuban(string nuban) {
            return base.Channel.GetAccountDetailsByNuban(nuban);
        }
        
        public System.Data.DataSet ConvertNubanToBanksFormat(string nuban) {
            return base.Channel.ConvertNubanToBanksFormat(nuban);
        }
        
        public System.Data.DataSet GetAccountDetails(string braCode, string cusNum, string curCode, string ledCode, string subAcctCode) {
            return base.Channel.GetAccountDetails(braCode, cusNum, curCode, ledCode, subAcctCode);
        }
        
        public System.Data.DataSet GetAccountDetails2(string braCode, string cusNum, string curCode, string ledCode, string subAcctCode) {
            return base.Channel.GetAccountDetails2(braCode, cusNum, curCode, ledCode, subAcctCode);
        }
        
        public bool IsTellerIDExists(string tellerid) {
            return base.Channel.IsTellerIDExists(tellerid);
        }
        
        public string getRegionalChannelCoordinatorUsernameForBranchCode(string bracode) {
            return base.Channel.getRegionalChannelCoordinatorUsernameForBranchCode(bracode);
        }
        
        public string isRegionalChannelCoordinatorForBranchCode(string username, string bracode) {
            return base.Channel.isRegionalChannelCoordinatorForBranchCode(username, bracode);
        }
        
        public string SendMail(string destinationEmail, string sourceEmail, string body, string subject) {
            return base.Channel.SendMail(destinationEmail, sourceEmail, body, subject);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BulktraImalJob.EWSService.SendMailWithAttachmentResponse BulktraImalJob.EWSService.ServiceSoap.SendMailWithAttachment(BulktraImalJob.EWSService.SendMailWithAttachmentRequest request) {
            return base.Channel.SendMailWithAttachment(request);
        }
        
        public string SendMailWithAttachment(string destinationEmail, string sourceEmail, string body, string subject, string ccEmailSeparatedByComma, byte[] attachmentData, string attachmentFilename) {
            BulktraImalJob.EWSService.SendMailWithAttachmentRequest inValue = new BulktraImalJob.EWSService.SendMailWithAttachmentRequest();
            inValue.destinationEmail = destinationEmail;
            inValue.sourceEmail = sourceEmail;
            inValue.body = body;
            inValue.subject = subject;
            inValue.ccEmailSeparatedByComma = ccEmailSeparatedByComma;
            inValue.attachmentData = attachmentData;
            inValue.attachmentFilename = attachmentFilename;
            BulktraImalJob.EWSService.SendMailWithAttachmentResponse retVal = ((BulktraImalJob.EWSService.ServiceSoap)(this)).SendMailWithAttachment(inValue);
            return retVal.SendMailWithAttachmentResult;
        }
        
        public bool IsTellerIDPasswordActive(string tellerid) {
            return base.Channel.IsTellerIDPasswordActive(tellerid);
        }
        
        public System.Data.DataSet GetAdDetailsByID(string StaffID) {
            return base.Channel.GetAdDetailsByID(StaffID);
        }
        
        public string Numbergenerate() {
            return base.Channel.Numbergenerate();
        }
        
        public string GetHighestRankedStaff(string[] staffusernames) {
            return base.Channel.GetHighestRankedStaff(staffusernames);
        }
        
        public string GetAllStaffGrade(string staffId) {
            return base.Channel.GetAllStaffGrade(staffId);
        }
        
        public string GetStaffGradeWithStaffID(string staffID) {
            return base.Channel.GetStaffGradeWithStaffID(staffID);
        }
        
        public System.Data.DataSet GetIMALCustByAcctNo(string cif_no) {
            return base.Channel.GetIMALCustByAcctNo(cif_no);
        }
        
        public System.Data.DataSet GetIMALCustByMobile(string mobile_234_format, string mobile_080_format) {
            return base.Channel.GetIMALCustByMobile(mobile_234_format, mobile_080_format);
        }
        
        public System.Data.DataSet GetBankCustByNuban(string nuban) {
            return base.Channel.GetBankCustByNuban(nuban);
        }
        
        public System.Data.DataSet GetAccountsByMobileNo(string mobileNo) {
            return base.Channel.GetAccountsByMobileNo(mobileNo);
        }
        
        public System.Data.DataSet GetBankCustByMobile(string mobile_234_format, string mobile_080_format) {
            return base.Channel.GetBankCustByMobile(mobile_234_format, mobile_080_format);
        }
        
        public string GetBankName(string bankCode) {
            return base.Channel.GetBankName(bankCode);
        }
        
        public System.Data.DataSet GetBankBVN(string nuban) {
            return base.Channel.GetBankBVN(nuban);
        }
        
        public System.Data.DataSet GetIMALBVN(string nuban) {
            return base.Channel.GetIMALBVN(nuban);
        }
        
        public System.Data.DataSet CheckNUBANForComplaint(string NUBAN) {
            return base.Channel.CheckNUBANForComplaint(NUBAN);
        }
        
        public System.Data.DataSet getAccountFullinfoAllForComplaint(string NUBAN) {
            return base.Channel.getAccountFullinfoAllForComplaint(NUBAN);
        }
        
        public System.Data.DataSet CheckAcct(string AccNum) {
            return base.Channel.CheckAcct(AccNum);
        }
        
        public string getClientsForIMAL(string rrr) {
            return base.Channel.getClientsForIMAL(rrr);
        }
        
        public System.Data.DataSet CheckNUBANOmImal(string NUBAN) {
            return base.Channel.CheckNUBANOmImal(NUBAN);
        }
        
        public string getcurrec(string cc) {
            return base.Channel.getcurrec(cc);
        }
        
        public System.Data.DataSet getAcctTypeFromBank(string bra_code, string cus_num, string cur_code, string led_code, string sub_led_code) {
            return base.Channel.getAcctTypeFromBank(bra_code, cus_num, cur_code, led_code, sub_led_code);
        }
        
        public string[] GetWorkflowTrackerExceptions() {
            return base.Channel.GetWorkflowTrackerExceptions();
        }
        
        public string IsUserOnLeave(string username) {
            return base.Channel.IsUserOnLeave(username);
        }
    }
}
