//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeUssdCharges.IBS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBS.IBSServicesSoap")]
    public interface IBSServicesSoap {
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridge", ReplyAction="*")]
        TakeUssdCharges.IBS.IBSBridgeResponse IBSBridge(TakeUssdCharges.IBS.IBSBridgeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridge", ReplyAction="*")]
        System.Threading.Tasks.Task<TakeUssdCharges.IBS.IBSBridgeResponse> IBSBridgeAsync(TakeUssdCharges.IBS.IBSBridgeRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridgeNE", ReplyAction="*")]
        TakeUssdCharges.IBS.IBSBridgeNEResponse IBSBridgeNE(TakeUssdCharges.IBS.IBSBridgeNERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridgeNE", ReplyAction="*")]
        System.Threading.Tasks.Task<TakeUssdCharges.IBS.IBSBridgeNEResponse> IBSBridgeNEAsync(TakeUssdCharges.IBS.IBSBridgeNERequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridge", Namespace="http://tempuri.org/", Order=0)]
        public TakeUssdCharges.IBS.IBSBridgeRequestBody Body;
        
        public IBSBridgeRequest() {
        }
        
        public IBSBridgeRequest(TakeUssdCharges.IBS.IBSBridgeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Appid;
        
        public IBSBridgeRequestBody() {
        }
        
        public IBSBridgeRequestBody(string request, int Appid) {
            this.request = request;
            this.Appid = Appid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridgeResponse", Namespace="http://tempuri.org/", Order=0)]
        public TakeUssdCharges.IBS.IBSBridgeResponseBody Body;
        
        public IBSBridgeResponse() {
        }
        
        public IBSBridgeResponse(TakeUssdCharges.IBS.IBSBridgeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IBSBridgeResult;
        
        public IBSBridgeResponseBody() {
        }
        
        public IBSBridgeResponseBody(string IBSBridgeResult) {
            this.IBSBridgeResult = IBSBridgeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeNERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridgeNE", Namespace="http://tempuri.org/", Order=0)]
        public TakeUssdCharges.IBS.IBSBridgeNERequestBody Body;
        
        public IBSBridgeNERequest() {
        }
        
        public IBSBridgeNERequest(TakeUssdCharges.IBS.IBSBridgeNERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeNERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Appid;
        
        public IBSBridgeNERequestBody() {
        }
        
        public IBSBridgeNERequestBody(string request, int Appid) {
            this.request = request;
            this.Appid = Appid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeNEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridgeNEResponse", Namespace="http://tempuri.org/", Order=0)]
        public TakeUssdCharges.IBS.IBSBridgeNEResponseBody Body;
        
        public IBSBridgeNEResponse() {
        }
        
        public IBSBridgeNEResponse(TakeUssdCharges.IBS.IBSBridgeNEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeNEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IBSBridgeNEResult;
        
        public IBSBridgeNEResponseBody() {
        }
        
        public IBSBridgeNEResponseBody(string IBSBridgeNEResult) {
            this.IBSBridgeNEResult = IBSBridgeNEResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBSServicesSoapChannel : TakeUssdCharges.IBS.IBSServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BSServicesSoapClient : System.ServiceModel.ClientBase<TakeUssdCharges.IBS.IBSServicesSoap>, TakeUssdCharges.IBS.IBSServicesSoap {
        
        public BSServicesSoapClient() {
        }
        
        public BSServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BSServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TakeUssdCharges.IBS.IBSBridgeResponse TakeUssdCharges.IBS.IBSServicesSoap.IBSBridge(TakeUssdCharges.IBS.IBSBridgeRequest request) {
            return base.Channel.IBSBridge(request);
        }
        
        public string IBSBridge(string request, int Appid) {
            TakeUssdCharges.IBS.IBSBridgeRequest inValue = new TakeUssdCharges.IBS.IBSBridgeRequest();
            inValue.Body = new TakeUssdCharges.IBS.IBSBridgeRequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            TakeUssdCharges.IBS.IBSBridgeResponse retVal = ((TakeUssdCharges.IBS.IBSServicesSoap)(this)).IBSBridge(inValue);
            return retVal.Body.IBSBridgeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TakeUssdCharges.IBS.IBSBridgeResponse> TakeUssdCharges.IBS.IBSServicesSoap.IBSBridgeAsync(TakeUssdCharges.IBS.IBSBridgeRequest request) {
            return base.Channel.IBSBridgeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TakeUssdCharges.IBS.IBSBridgeResponse> IBSBridgeAsync(string request, int Appid) {
            TakeUssdCharges.IBS.IBSBridgeRequest inValue = new TakeUssdCharges.IBS.IBSBridgeRequest();
            inValue.Body = new TakeUssdCharges.IBS.IBSBridgeRequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            return ((TakeUssdCharges.IBS.IBSServicesSoap)(this)).IBSBridgeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TakeUssdCharges.IBS.IBSBridgeNEResponse TakeUssdCharges.IBS.IBSServicesSoap.IBSBridgeNE(TakeUssdCharges.IBS.IBSBridgeNERequest request) {
            return base.Channel.IBSBridgeNE(request);
        }
        
        public string IBSBridgeNE(string request, int Appid) {
            TakeUssdCharges.IBS.IBSBridgeNERequest inValue = new TakeUssdCharges.IBS.IBSBridgeNERequest();
            inValue.Body = new TakeUssdCharges.IBS.IBSBridgeNERequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            TakeUssdCharges.IBS.IBSBridgeNEResponse retVal = ((TakeUssdCharges.IBS.IBSServicesSoap)(this)).IBSBridgeNE(inValue);
            return retVal.Body.IBSBridgeNEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TakeUssdCharges.IBS.IBSBridgeNEResponse> TakeUssdCharges.IBS.IBSServicesSoap.IBSBridgeNEAsync(TakeUssdCharges.IBS.IBSBridgeNERequest request) {
            return base.Channel.IBSBridgeNEAsync(request);
        }
        
        public System.Threading.Tasks.Task<TakeUssdCharges.IBS.IBSBridgeNEResponse> IBSBridgeNEAsync(string request, int Appid) {
            TakeUssdCharges.IBS.IBSBridgeNERequest inValue = new TakeUssdCharges.IBS.IBSBridgeNERequest();
            inValue.Body = new TakeUssdCharges.IBS.IBSBridgeNERequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            return ((TakeUssdCharges.IBS.IBSServicesSoap)(this)).IBSBridgeNEAsync(inValue);
        }
    }
}
