//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubbleJob
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public string T24ID { get; set; }
        public string Company_Name { get; set; }
        public string Mnemonic { get; set; }
        public string Sub_Div_Code { get; set; }
        public string Bra_Code { get; set; }
        public string Address { get; set; }
    }
}
