<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:tns="http://ws.merchantpay.nibss.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" name="merchantEnrollment" targetNamespace="http://ws.merchantpay.nibss.com/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="http://192.234.10.204:8564/merchantpay/merchant-enrollment?xsd=1" namespace="http://ws.merchantpay.nibss.com/" />
    </xsd:schema>
  </types>
  <message name="MerchantEnrollment">
    <part name="parameters" element="tns:MerchantEnrollment" />
  </message>
  <message name="MerchantEnrollmentResponse">
    <part name="parameters" element="tns:MerchantEnrollmentResponse" />
  </message>
  <message name="MerchantNameEnquiry">
    <part name="parameters" element="tns:MerchantNameEnquiry" />
  </message>
  <message name="MerchantNameEnquiryResponse">
    <part name="parameters" element="tns:MerchantNameEnquiryResponse" />
  </message>
  <portType name="MerchantEnrollmentEndPoint">
    <operation name="MerchantEnrollment">
      <input wsam:Action="http://ws.merchantpay.nibss.com/MerchantEnrollmentEndPoint/MerchantEnrollmentRequest" message="tns:MerchantEnrollment" />
      <output wsam:Action="http://ws.merchantpay.nibss.com/MerchantEnrollmentEndPoint/MerchantEnrollmentResponse" message="tns:MerchantEnrollmentResponse" />
    </operation>
    <operation name="MerchantNameEnquiry">
      <input wsam:Action="http://ws.merchantpay.nibss.com/MerchantEnrollmentEndPoint/MerchantNameEnquiryRequest" message="tns:MerchantNameEnquiry" />
      <output wsam:Action="http://ws.merchantpay.nibss.com/MerchantEnrollmentEndPoint/MerchantNameEnquiryResponse" message="tns:MerchantNameEnquiryResponse" />
    </operation>
  </portType>
  <binding name="MerchantEnrollmentEndPointPortBinding" type="tns:MerchantEnrollmentEndPoint">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="MerchantEnrollment">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="MerchantNameEnquiry">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  <service name="merchantEnrollment">
    <port name="MerchantEnrollmentEndPointPort" binding="tns:MerchantEnrollmentEndPointPortBinding">
      <soap:address location="http://192.234.10.204:8564/merchantpay/merchant-enrollment" />
    </port>
  </service>
</definitions>