//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BankTellerFundsTransfer_imal.ImalAcctinfo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AccountLookUpOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountTagOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountUnTagOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountsListByIntroducerOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountByAccountNumberOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::BankTellerFundsTransfer_imal.Properties.Settings.Default.BankTellerFundsTransfer_lagos3_ImalAcctinfo_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AccountLookUpCompletedEventHandler AccountLookUpCompleted;
        
        /// <remarks/>
        public event AccountTagCompletedEventHandler AccountTagCompleted;
        
        /// <remarks/>
        public event AccountUnTagCompletedEventHandler AccountUnTagCompleted;
        
        /// <remarks/>
        public event AccountsListByIntroducerCompletedEventHandler AccountsListByIntroducerCompleted;
        
        /// <remarks/>
        public event AccountTypesCompletedEventHandler AccountTypesCompleted;
        
        /// <remarks/>
        public event GetAccountByAccountNumberCompletedEventHandler GetAccountByAccountNumberCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountLookUp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AccountLookUp(string acctnumber, string cbs) {
            object[] results = this.Invoke("AccountLookUp", new object[] {
                        acctnumber,
                        cbs});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AccountLookUpAsync(string acctnumber, string cbs) {
            this.AccountLookUpAsync(acctnumber, cbs, null);
        }
        
        /// <remarks/>
        public void AccountLookUpAsync(string acctnumber, string cbs, object userState) {
            if ((this.AccountLookUpOperationCompleted == null)) {
                this.AccountLookUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountLookUpOperationCompleted);
            }
            this.InvokeAsync("AccountLookUp", new object[] {
                        acctnumber,
                        cbs}, this.AccountLookUpOperationCompleted, userState);
        }
        
        private void OnAccountLookUpOperationCompleted(object arg) {
            if ((this.AccountLookUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountLookUpCompleted(this, new AccountLookUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountTag", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AccountTag(string acctnumber, string cbs, string officer) {
            object[] results = this.Invoke("AccountTag", new object[] {
                        acctnumber,
                        cbs,
                        officer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AccountTagAsync(string acctnumber, string cbs, string officer) {
            this.AccountTagAsync(acctnumber, cbs, officer, null);
        }
        
        /// <remarks/>
        public void AccountTagAsync(string acctnumber, string cbs, string officer, object userState) {
            if ((this.AccountTagOperationCompleted == null)) {
                this.AccountTagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountTagOperationCompleted);
            }
            this.InvokeAsync("AccountTag", new object[] {
                        acctnumber,
                        cbs,
                        officer}, this.AccountTagOperationCompleted, userState);
        }
        
        private void OnAccountTagOperationCompleted(object arg) {
            if ((this.AccountTagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountTagCompleted(this, new AccountTagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountUnTag", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AccountUnTag(string acctnumber, string cbs, string officer) {
            object[] results = this.Invoke("AccountUnTag", new object[] {
                        acctnumber,
                        cbs,
                        officer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AccountUnTagAsync(string acctnumber, string cbs, string officer) {
            this.AccountUnTagAsync(acctnumber, cbs, officer, null);
        }
        
        /// <remarks/>
        public void AccountUnTagAsync(string acctnumber, string cbs, string officer, object userState) {
            if ((this.AccountUnTagOperationCompleted == null)) {
                this.AccountUnTagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountUnTagOperationCompleted);
            }
            this.InvokeAsync("AccountUnTag", new object[] {
                        acctnumber,
                        cbs,
                        officer}, this.AccountUnTagOperationCompleted, userState);
        }
        
        private void OnAccountUnTagOperationCompleted(object arg) {
            if ((this.AccountUnTagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountUnTagCompleted(this, new AccountUnTagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountsListByIntroducer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AccountsListByIntroducer(string cbs, string officer, string introtype) {
            object[] results = this.Invoke("AccountsListByIntroducer", new object[] {
                        cbs,
                        officer,
                        introtype});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AccountsListByIntroducerAsync(string cbs, string officer, string introtype) {
            this.AccountsListByIntroducerAsync(cbs, officer, introtype, null);
        }
        
        /// <remarks/>
        public void AccountsListByIntroducerAsync(string cbs, string officer, string introtype, object userState) {
            if ((this.AccountsListByIntroducerOperationCompleted == null)) {
                this.AccountsListByIntroducerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountsListByIntroducerOperationCompleted);
            }
            this.InvokeAsync("AccountsListByIntroducer", new object[] {
                        cbs,
                        officer,
                        introtype}, this.AccountsListByIntroducerOperationCompleted, userState);
        }
        
        private void OnAccountsListByIntroducerOperationCompleted(object arg) {
            if ((this.AccountsListByIntroducerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountsListByIntroducerCompleted(this, new AccountsListByIntroducerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountTypes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AccountTypes(string cbs) {
            object[] results = this.Invoke("AccountTypes", new object[] {
                        cbs});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AccountTypesAsync(string cbs) {
            this.AccountTypesAsync(cbs, null);
        }
        
        /// <remarks/>
        public void AccountTypesAsync(string cbs, object userState) {
            if ((this.AccountTypesOperationCompleted == null)) {
                this.AccountTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountTypesOperationCompleted);
            }
            this.InvokeAsync("AccountTypes", new object[] {
                        cbs}, this.AccountTypesOperationCompleted, userState);
        }
        
        private void OnAccountTypesOperationCompleted(object arg) {
            if ((this.AccountTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountTypesCompleted(this, new AccountTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccountByAccountNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAccountByAccountNumber(string acctnumber) {
            object[] results = this.Invoke("GetAccountByAccountNumber", new object[] {
                        acctnumber});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountByAccountNumberAsync(string acctnumber) {
            this.GetAccountByAccountNumberAsync(acctnumber, null);
        }
        
        /// <remarks/>
        public void GetAccountByAccountNumberAsync(string acctnumber, object userState) {
            if ((this.GetAccountByAccountNumberOperationCompleted == null)) {
                this.GetAccountByAccountNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountByAccountNumberOperationCompleted);
            }
            this.InvokeAsync("GetAccountByAccountNumber", new object[] {
                        acctnumber}, this.GetAccountByAccountNumberOperationCompleted, userState);
        }
        
        private void OnGetAccountByAccountNumberOperationCompleted(object arg) {
            if ((this.GetAccountByAccountNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountByAccountNumberCompleted(this, new GetAccountByAccountNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void AccountLookUpCompletedEventHandler(object sender, AccountLookUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountLookUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountLookUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void AccountTagCompletedEventHandler(object sender, AccountTagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountTagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountTagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void AccountUnTagCompletedEventHandler(object sender, AccountUnTagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountUnTagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountUnTagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void AccountsListByIntroducerCompletedEventHandler(object sender, AccountsListByIntroducerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountsListByIntroducerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountsListByIntroducerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void AccountTypesCompletedEventHandler(object sender, AccountTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetAccountByAccountNumberCompletedEventHandler(object sender, GetAccountByAccountNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountByAccountNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountByAccountNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591