//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace imalChannelWS.imalcore {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="imalcore.ServicesSoap")]
    public interface ServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountValidation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AccountValidation(string acctnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountValidation", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AccountValidationAsync(string acctnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FundstransFer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FundstransFer(string fromacct, string toacct, decimal amt, string remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FundstransFer", ReplyAction="*")]
        System.Threading.Tasks.Task<string> FundstransFerAsync(string fromacct, string toacct, decimal amt, string remarks);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicesSoapChannel : imalChannelWS.imalcore.ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesSoapClient : System.ServiceModel.ClientBase<imalChannelWS.imalcore.ServicesSoap>, imalChannelWS.imalcore.ServicesSoap {
        
        public ServicesSoapClient() {
        }
        
        public ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet AccountValidation(string acctnumber) {
            return base.Channel.AccountValidation(acctnumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AccountValidationAsync(string acctnumber) {
            return base.Channel.AccountValidationAsync(acctnumber);
        }
        
        public string FundstransFer(string fromacct, string toacct, decimal amt, string remarks) {
            return base.Channel.FundstransFer(fromacct, toacct, amt, remarks);
        }
        
        public System.Threading.Tasks.Task<string> FundstransFerAsync(string fromacct, string toacct, decimal amt, string remarks) {
            return base.Channel.FundstransFerAsync(fromacct, toacct, amt, remarks);
        }
    }
}
