//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtpService.ft {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ft.ft_genericSoap")]
    public interface ft_genericSoap {
        
        // CODEGEN: Generating message contract since element name txt from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkRequestX", ReplyAction="*")]
        OtpService.ft.checkRequestXResponse checkRequestX(OtpService.ft.checkRequestXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkRequestX", ReplyAction="*")]
        System.Threading.Tasks.Task<OtpService.ft.checkRequestXResponse> checkRequestXAsync(OtpService.ft.checkRequestXRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/performFundsTransferDebitPlAccount", ReplyAction="*")]
        OtpService.ft.performFundsTransferDebitPlAccountResponse performFundsTransferDebitPlAccount(OtpService.ft.performFundsTransferDebitPlAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/performFundsTransferDebitPlAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<OtpService.ft.performFundsTransferDebitPlAccountResponse> performFundsTransferDebitPlAccountAsync(OtpService.ft.performFundsTransferDebitPlAccountRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/performFundsTransfer", ReplyAction="*")]
        OtpService.ft.performFundsTransferResponse performFundsTransfer(OtpService.ft.performFundsTransferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/performFundsTransfer", ReplyAction="*")]
        System.Threading.Tasks.Task<OtpService.ft.performFundsTransferResponse> performFundsTransferAsync(OtpService.ft.performFundsTransferRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/performFundsTransferExchange", ReplyAction="*")]
        OtpService.ft.performFundsTransferExchangeResponse performFundsTransferExchange(OtpService.ft.performFundsTransferExchangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/performFundsTransferExchange", ReplyAction="*")]
        System.Threading.Tasks.Task<OtpService.ft.performFundsTransferExchangeResponse> performFundsTransferExchangeAsync(OtpService.ft.performFundsTransferExchangeRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/performFundsTransferOverdraw", ReplyAction="*")]
        OtpService.ft.performFundsTransferOverdrawResponse performFundsTransferOverdraw(OtpService.ft.performFundsTransferOverdrawRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/performFundsTransferOverdraw", ReplyAction="*")]
        System.Threading.Tasks.Task<OtpService.ft.performFundsTransferOverdrawResponse> performFundsTransferOverdrawAsync(OtpService.ft.performFundsTransferOverdrawRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/performFundsTransferWithSenderBvn", ReplyAction="*")]
        OtpService.ft.performFundsTransferWithSenderBvnResponse performFundsTransferWithSenderBvn(OtpService.ft.performFundsTransferWithSenderBvnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/performFundsTransferWithSenderBvn", ReplyAction="*")]
        System.Threading.Tasks.Task<OtpService.ft.performFundsTransferWithSenderBvnResponse> performFundsTransferWithSenderBvnAsync(OtpService.ft.performFundsTransferWithSenderBvnRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/performFundsTransferWithSwift", ReplyAction="*")]
        OtpService.ft.performFundsTransferWithSwiftResponse performFundsTransferWithSwift(OtpService.ft.performFundsTransferWithSwiftRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/performFundsTransferWithSwift", ReplyAction="*")]
        System.Threading.Tasks.Task<OtpService.ft.performFundsTransferWithSwiftResponse> performFundsTransferWithSwiftAsync(OtpService.ft.performFundsTransferWithSwiftRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkRequestXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkRequestX", Namespace="http://tempuri.org/", Order=0)]
        public OtpService.ft.checkRequestXRequestBody Body;
        
        public checkRequestXRequest() {
        }
        
        public checkRequestXRequest(OtpService.ft.checkRequestXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkRequestXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string txt;
        
        public checkRequestXRequestBody() {
        }
        
        public checkRequestXRequestBody(string txt) {
            this.txt = txt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkRequestXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkRequestXResponse", Namespace="http://tempuri.org/", Order=0)]
        public OtpService.ft.checkRequestXResponseBody Body;
        
        public checkRequestXResponse() {
        }
        
        public checkRequestXResponse(OtpService.ft.checkRequestXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkRequestXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string checkRequestXResult;
        
        public checkRequestXResponseBody() {
        }
        
        public checkRequestXResponseBody(string checkRequestXResult) {
            this.checkRequestXResult = checkRequestXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class performFundsTransferDebitPlAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="performFundsTransferDebitPlAccount", Namespace="http://tempuri.org/", Order=0)]
        public OtpService.ft.performFundsTransferDebitPlAccountRequestBody Body;
        
        public performFundsTransferDebitPlAccountRequest() {
        }
        
        public performFundsTransferDebitPlAccountRequest(OtpService.ft.performFundsTransferDebitPlAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class performFundsTransferDebitPlAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string trnxType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string profitCentreCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string endpointApp;
        
        public performFundsTransferDebitPlAccountRequestBody() {
        }
        
        public performFundsTransferDebitPlAccountRequestBody(string xml, string trnxType, string profitCentreCode, string endpointApp) {
            this.xml = xml;
            this.trnxType = trnxType;
            this.profitCentreCode = profitCentreCode;
            this.endpointApp = endpointApp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class performFundsTransferDebitPlAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="performFundsTransferDebitPlAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public OtpService.ft.performFundsTransferDebitPlAccountResponseBody Body;
        
        public performFundsTransferDebitPlAccountResponse() {
        }
        
        public performFundsTransferDebitPlAccountResponse(OtpService.ft.performFundsTransferDebitPlAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class performFundsTransferDebitPlAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string performFundsTransferDebitPlAccountResult;
        
        public performFundsTransferDebitPlAccountResponseBody() {
        }
        
        public performFundsTransferDebitPlAccountResponseBody(string performFundsTransferDebitPlAccountResult) {
            this.performFundsTransferDebitPlAccountResult = performFundsTransferDebitPlAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class performFundsTransferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="performFundsTransfer", Namespace="http://tempuri.org/", Order=0)]
        public OtpService.ft.performFundsTransferRequestBody Body;
        
        public performFundsTransferRequest() {
        }
        
        public performFundsTransferRequest(OtpService.ft.performFundsTransferRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class performFundsTransferRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string trnxType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string endpointApp;
        
        public performFundsTransferRequestBody() {
        }
        
        public performFundsTransferRequestBody(string xml, string trnxType, string endpointApp) {
            this.xml = xml;
            this.trnxType = trnxType;
            this.endpointApp = endpointApp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class performFundsTransferResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="performFundsTransferResponse", Namespace="http://tempuri.org/", Order=0)]
        public OtpService.ft.performFundsTransferResponseBody Body;
        
        public performFundsTransferResponse() {
        }
        
        public performFundsTransferResponse(OtpService.ft.performFundsTransferResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class performFundsTransferResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string performFundsTransferResult;
        
        public performFundsTransferResponseBody() {
        }
        
        public performFundsTransferResponseBody(string performFundsTransferResult) {
            this.performFundsTransferResult = performFundsTransferResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class performFundsTransferExchangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="performFundsTransferExchange", Namespace="http://tempuri.org/", Order=0)]
        public OtpService.ft.performFundsTransferExchangeRequestBody Body;
        
        public performFundsTransferExchangeRequest() {
        }
        
        public performFundsTransferExchangeRequest(OtpService.ft.performFundsTransferExchangeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class performFundsTransferExchangeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string trnxType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal rate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string endpointApp;
        
        public performFundsTransferExchangeRequestBody() {
        }
        
        public performFundsTransferExchangeRequestBody(string xml, string trnxType, decimal rate, string endpointApp) {
            this.xml = xml;
            this.trnxType = trnxType;
            this.rate = rate;
            this.endpointApp = endpointApp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class performFundsTransferExchangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="performFundsTransferExchangeResponse", Namespace="http://tempuri.org/", Order=0)]
        public OtpService.ft.performFundsTransferExchangeResponseBody Body;
        
        public performFundsTransferExchangeResponse() {
        }
        
        public performFundsTransferExchangeResponse(OtpService.ft.performFundsTransferExchangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class performFundsTransferExchangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string performFundsTransferExchangeResult;
        
        public performFundsTransferExchangeResponseBody() {
        }
        
        public performFundsTransferExchangeResponseBody(string performFundsTransferExchangeResult) {
            this.performFundsTransferExchangeResult = performFundsTransferExchangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class performFundsTransferOverdrawRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="performFundsTransferOverdraw", Namespace="http://tempuri.org/", Order=0)]
        public OtpService.ft.performFundsTransferOverdrawRequestBody Body;
        
        public performFundsTransferOverdrawRequest() {
        }
        
        public performFundsTransferOverdrawRequest(OtpService.ft.performFundsTransferOverdrawRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class performFundsTransferOverdrawRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string trnxType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string endpointApp;
        
        public performFundsTransferOverdrawRequestBody() {
        }
        
        public performFundsTransferOverdrawRequestBody(string xml, string trnxType, string endpointApp) {
            this.xml = xml;
            this.trnxType = trnxType;
            this.endpointApp = endpointApp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class performFundsTransferOverdrawResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="performFundsTransferOverdrawResponse", Namespace="http://tempuri.org/", Order=0)]
        public OtpService.ft.performFundsTransferOverdrawResponseBody Body;
        
        public performFundsTransferOverdrawResponse() {
        }
        
        public performFundsTransferOverdrawResponse(OtpService.ft.performFundsTransferOverdrawResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class performFundsTransferOverdrawResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string performFundsTransferOverdrawResult;
        
        public performFundsTransferOverdrawResponseBody() {
        }
        
        public performFundsTransferOverdrawResponseBody(string performFundsTransferOverdrawResult) {
            this.performFundsTransferOverdrawResult = performFundsTransferOverdrawResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class performFundsTransferWithSenderBvnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="performFundsTransferWithSenderBvn", Namespace="http://tempuri.org/", Order=0)]
        public OtpService.ft.performFundsTransferWithSenderBvnRequestBody Body;
        
        public performFundsTransferWithSenderBvnRequest() {
        }
        
        public performFundsTransferWithSenderBvnRequest(OtpService.ft.performFundsTransferWithSenderBvnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class performFundsTransferWithSenderBvnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string trnxType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string senderBvn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string endpointApp;
        
        public performFundsTransferWithSenderBvnRequestBody() {
        }
        
        public performFundsTransferWithSenderBvnRequestBody(string xml, string trnxType, string senderBvn, string endpointApp) {
            this.xml = xml;
            this.trnxType = trnxType;
            this.senderBvn = senderBvn;
            this.endpointApp = endpointApp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class performFundsTransferWithSenderBvnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="performFundsTransferWithSenderBvnResponse", Namespace="http://tempuri.org/", Order=0)]
        public OtpService.ft.performFundsTransferWithSenderBvnResponseBody Body;
        
        public performFundsTransferWithSenderBvnResponse() {
        }
        
        public performFundsTransferWithSenderBvnResponse(OtpService.ft.performFundsTransferWithSenderBvnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class performFundsTransferWithSenderBvnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string performFundsTransferWithSenderBvnResult;
        
        public performFundsTransferWithSenderBvnResponseBody() {
        }
        
        public performFundsTransferWithSenderBvnResponseBody(string performFundsTransferWithSenderBvnResult) {
            this.performFundsTransferWithSenderBvnResult = performFundsTransferWithSenderBvnResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class performFundsTransferWithSwiftRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="performFundsTransferWithSwift", Namespace="http://tempuri.org/", Order=0)]
        public OtpService.ft.performFundsTransferWithSwiftRequestBody Body;
        
        public performFundsTransferWithSwiftRequest() {
        }
        
        public performFundsTransferWithSwiftRequest(OtpService.ft.performFundsTransferWithSwiftRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class performFundsTransferWithSwiftRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string trnxType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string inwardSenderBic;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string swiftField20;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime debitValueDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime creditValueDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string endpointApp;
        
        public performFundsTransferWithSwiftRequestBody() {
        }
        
        public performFundsTransferWithSwiftRequestBody(string xml, string trnxType, string inwardSenderBic, string swiftField20, System.DateTime debitValueDate, System.DateTime creditValueDate, string endpointApp) {
            this.xml = xml;
            this.trnxType = trnxType;
            this.inwardSenderBic = inwardSenderBic;
            this.swiftField20 = swiftField20;
            this.debitValueDate = debitValueDate;
            this.creditValueDate = creditValueDate;
            this.endpointApp = endpointApp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class performFundsTransferWithSwiftResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="performFundsTransferWithSwiftResponse", Namespace="http://tempuri.org/", Order=0)]
        public OtpService.ft.performFundsTransferWithSwiftResponseBody Body;
        
        public performFundsTransferWithSwiftResponse() {
        }
        
        public performFundsTransferWithSwiftResponse(OtpService.ft.performFundsTransferWithSwiftResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class performFundsTransferWithSwiftResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string performFundsTransferWithSwiftResult;
        
        public performFundsTransferWithSwiftResponseBody() {
        }
        
        public performFundsTransferWithSwiftResponseBody(string performFundsTransferWithSwiftResult) {
            this.performFundsTransferWithSwiftResult = performFundsTransferWithSwiftResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ft_genericSoapChannel : OtpService.ft.ft_genericSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ft_genericSoapClient : System.ServiceModel.ClientBase<OtpService.ft.ft_genericSoap>, OtpService.ft.ft_genericSoap {
        
        public ft_genericSoapClient() {
        }
        
        public ft_genericSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ft_genericSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ft_genericSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ft_genericSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OtpService.ft.checkRequestXResponse OtpService.ft.ft_genericSoap.checkRequestX(OtpService.ft.checkRequestXRequest request) {
            return base.Channel.checkRequestX(request);
        }
        
        public string checkRequestX(string txt) {
            OtpService.ft.checkRequestXRequest inValue = new OtpService.ft.checkRequestXRequest();
            inValue.Body = new OtpService.ft.checkRequestXRequestBody();
            inValue.Body.txt = txt;
            OtpService.ft.checkRequestXResponse retVal = ((OtpService.ft.ft_genericSoap)(this)).checkRequestX(inValue);
            return retVal.Body.checkRequestXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OtpService.ft.checkRequestXResponse> OtpService.ft.ft_genericSoap.checkRequestXAsync(OtpService.ft.checkRequestXRequest request) {
            return base.Channel.checkRequestXAsync(request);
        }
        
        public System.Threading.Tasks.Task<OtpService.ft.checkRequestXResponse> checkRequestXAsync(string txt) {
            OtpService.ft.checkRequestXRequest inValue = new OtpService.ft.checkRequestXRequest();
            inValue.Body = new OtpService.ft.checkRequestXRequestBody();
            inValue.Body.txt = txt;
            return ((OtpService.ft.ft_genericSoap)(this)).checkRequestXAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OtpService.ft.performFundsTransferDebitPlAccountResponse OtpService.ft.ft_genericSoap.performFundsTransferDebitPlAccount(OtpService.ft.performFundsTransferDebitPlAccountRequest request) {
            return base.Channel.performFundsTransferDebitPlAccount(request);
        }
        
        public string performFundsTransferDebitPlAccount(string xml, string trnxType, string profitCentreCode, string endpointApp) {
            OtpService.ft.performFundsTransferDebitPlAccountRequest inValue = new OtpService.ft.performFundsTransferDebitPlAccountRequest();
            inValue.Body = new OtpService.ft.performFundsTransferDebitPlAccountRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.profitCentreCode = profitCentreCode;
            inValue.Body.endpointApp = endpointApp;
            OtpService.ft.performFundsTransferDebitPlAccountResponse retVal = ((OtpService.ft.ft_genericSoap)(this)).performFundsTransferDebitPlAccount(inValue);
            return retVal.Body.performFundsTransferDebitPlAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OtpService.ft.performFundsTransferDebitPlAccountResponse> OtpService.ft.ft_genericSoap.performFundsTransferDebitPlAccountAsync(OtpService.ft.performFundsTransferDebitPlAccountRequest request) {
            return base.Channel.performFundsTransferDebitPlAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<OtpService.ft.performFundsTransferDebitPlAccountResponse> performFundsTransferDebitPlAccountAsync(string xml, string trnxType, string profitCentreCode, string endpointApp) {
            OtpService.ft.performFundsTransferDebitPlAccountRequest inValue = new OtpService.ft.performFundsTransferDebitPlAccountRequest();
            inValue.Body = new OtpService.ft.performFundsTransferDebitPlAccountRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.profitCentreCode = profitCentreCode;
            inValue.Body.endpointApp = endpointApp;
            return ((OtpService.ft.ft_genericSoap)(this)).performFundsTransferDebitPlAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OtpService.ft.performFundsTransferResponse OtpService.ft.ft_genericSoap.performFundsTransfer(OtpService.ft.performFundsTransferRequest request) {
            return base.Channel.performFundsTransfer(request);
        }
        
        public string performFundsTransfer(string xml, string trnxType, string endpointApp) {
            OtpService.ft.performFundsTransferRequest inValue = new OtpService.ft.performFundsTransferRequest();
            inValue.Body = new OtpService.ft.performFundsTransferRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.endpointApp = endpointApp;
            OtpService.ft.performFundsTransferResponse retVal = ((OtpService.ft.ft_genericSoap)(this)).performFundsTransfer(inValue);
            return retVal.Body.performFundsTransferResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OtpService.ft.performFundsTransferResponse> OtpService.ft.ft_genericSoap.performFundsTransferAsync(OtpService.ft.performFundsTransferRequest request) {
            return base.Channel.performFundsTransferAsync(request);
        }
        
        public System.Threading.Tasks.Task<OtpService.ft.performFundsTransferResponse> performFundsTransferAsync(string xml, string trnxType, string endpointApp) {
            OtpService.ft.performFundsTransferRequest inValue = new OtpService.ft.performFundsTransferRequest();
            inValue.Body = new OtpService.ft.performFundsTransferRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.endpointApp = endpointApp;
            return ((OtpService.ft.ft_genericSoap)(this)).performFundsTransferAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OtpService.ft.performFundsTransferExchangeResponse OtpService.ft.ft_genericSoap.performFundsTransferExchange(OtpService.ft.performFundsTransferExchangeRequest request) {
            return base.Channel.performFundsTransferExchange(request);
        }
        
        public string performFundsTransferExchange(string xml, string trnxType, decimal rate, string endpointApp) {
            OtpService.ft.performFundsTransferExchangeRequest inValue = new OtpService.ft.performFundsTransferExchangeRequest();
            inValue.Body = new OtpService.ft.performFundsTransferExchangeRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.rate = rate;
            inValue.Body.endpointApp = endpointApp;
            OtpService.ft.performFundsTransferExchangeResponse retVal = ((OtpService.ft.ft_genericSoap)(this)).performFundsTransferExchange(inValue);
            return retVal.Body.performFundsTransferExchangeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OtpService.ft.performFundsTransferExchangeResponse> OtpService.ft.ft_genericSoap.performFundsTransferExchangeAsync(OtpService.ft.performFundsTransferExchangeRequest request) {
            return base.Channel.performFundsTransferExchangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<OtpService.ft.performFundsTransferExchangeResponse> performFundsTransferExchangeAsync(string xml, string trnxType, decimal rate, string endpointApp) {
            OtpService.ft.performFundsTransferExchangeRequest inValue = new OtpService.ft.performFundsTransferExchangeRequest();
            inValue.Body = new OtpService.ft.performFundsTransferExchangeRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.rate = rate;
            inValue.Body.endpointApp = endpointApp;
            return ((OtpService.ft.ft_genericSoap)(this)).performFundsTransferExchangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OtpService.ft.performFundsTransferOverdrawResponse OtpService.ft.ft_genericSoap.performFundsTransferOverdraw(OtpService.ft.performFundsTransferOverdrawRequest request) {
            return base.Channel.performFundsTransferOverdraw(request);
        }
        
        public string performFundsTransferOverdraw(string xml, string trnxType, string endpointApp) {
            OtpService.ft.performFundsTransferOverdrawRequest inValue = new OtpService.ft.performFundsTransferOverdrawRequest();
            inValue.Body = new OtpService.ft.performFundsTransferOverdrawRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.endpointApp = endpointApp;
            OtpService.ft.performFundsTransferOverdrawResponse retVal = ((OtpService.ft.ft_genericSoap)(this)).performFundsTransferOverdraw(inValue);
            return retVal.Body.performFundsTransferOverdrawResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OtpService.ft.performFundsTransferOverdrawResponse> OtpService.ft.ft_genericSoap.performFundsTransferOverdrawAsync(OtpService.ft.performFundsTransferOverdrawRequest request) {
            return base.Channel.performFundsTransferOverdrawAsync(request);
        }
        
        public System.Threading.Tasks.Task<OtpService.ft.performFundsTransferOverdrawResponse> performFundsTransferOverdrawAsync(string xml, string trnxType, string endpointApp) {
            OtpService.ft.performFundsTransferOverdrawRequest inValue = new OtpService.ft.performFundsTransferOverdrawRequest();
            inValue.Body = new OtpService.ft.performFundsTransferOverdrawRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.endpointApp = endpointApp;
            return ((OtpService.ft.ft_genericSoap)(this)).performFundsTransferOverdrawAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OtpService.ft.performFundsTransferWithSenderBvnResponse OtpService.ft.ft_genericSoap.performFundsTransferWithSenderBvn(OtpService.ft.performFundsTransferWithSenderBvnRequest request) {
            return base.Channel.performFundsTransferWithSenderBvn(request);
        }
        
        public string performFundsTransferWithSenderBvn(string xml, string trnxType, string senderBvn, string endpointApp) {
            OtpService.ft.performFundsTransferWithSenderBvnRequest inValue = new OtpService.ft.performFundsTransferWithSenderBvnRequest();
            inValue.Body = new OtpService.ft.performFundsTransferWithSenderBvnRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.senderBvn = senderBvn;
            inValue.Body.endpointApp = endpointApp;
            OtpService.ft.performFundsTransferWithSenderBvnResponse retVal = ((OtpService.ft.ft_genericSoap)(this)).performFundsTransferWithSenderBvn(inValue);
            return retVal.Body.performFundsTransferWithSenderBvnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OtpService.ft.performFundsTransferWithSenderBvnResponse> OtpService.ft.ft_genericSoap.performFundsTransferWithSenderBvnAsync(OtpService.ft.performFundsTransferWithSenderBvnRequest request) {
            return base.Channel.performFundsTransferWithSenderBvnAsync(request);
        }
        
        public System.Threading.Tasks.Task<OtpService.ft.performFundsTransferWithSenderBvnResponse> performFundsTransferWithSenderBvnAsync(string xml, string trnxType, string senderBvn, string endpointApp) {
            OtpService.ft.performFundsTransferWithSenderBvnRequest inValue = new OtpService.ft.performFundsTransferWithSenderBvnRequest();
            inValue.Body = new OtpService.ft.performFundsTransferWithSenderBvnRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.senderBvn = senderBvn;
            inValue.Body.endpointApp = endpointApp;
            return ((OtpService.ft.ft_genericSoap)(this)).performFundsTransferWithSenderBvnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OtpService.ft.performFundsTransferWithSwiftResponse OtpService.ft.ft_genericSoap.performFundsTransferWithSwift(OtpService.ft.performFundsTransferWithSwiftRequest request) {
            return base.Channel.performFundsTransferWithSwift(request);
        }
        
        public string performFundsTransferWithSwift(string xml, string trnxType, string inwardSenderBic, string swiftField20, System.DateTime debitValueDate, System.DateTime creditValueDate, string endpointApp) {
            OtpService.ft.performFundsTransferWithSwiftRequest inValue = new OtpService.ft.performFundsTransferWithSwiftRequest();
            inValue.Body = new OtpService.ft.performFundsTransferWithSwiftRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.inwardSenderBic = inwardSenderBic;
            inValue.Body.swiftField20 = swiftField20;
            inValue.Body.debitValueDate = debitValueDate;
            inValue.Body.creditValueDate = creditValueDate;
            inValue.Body.endpointApp = endpointApp;
            OtpService.ft.performFundsTransferWithSwiftResponse retVal = ((OtpService.ft.ft_genericSoap)(this)).performFundsTransferWithSwift(inValue);
            return retVal.Body.performFundsTransferWithSwiftResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OtpService.ft.performFundsTransferWithSwiftResponse> OtpService.ft.ft_genericSoap.performFundsTransferWithSwiftAsync(OtpService.ft.performFundsTransferWithSwiftRequest request) {
            return base.Channel.performFundsTransferWithSwiftAsync(request);
        }
        
        public System.Threading.Tasks.Task<OtpService.ft.performFundsTransferWithSwiftResponse> performFundsTransferWithSwiftAsync(string xml, string trnxType, string inwardSenderBic, string swiftField20, System.DateTime debitValueDate, System.DateTime creditValueDate, string endpointApp) {
            OtpService.ft.performFundsTransferWithSwiftRequest inValue = new OtpService.ft.performFundsTransferWithSwiftRequest();
            inValue.Body = new OtpService.ft.performFundsTransferWithSwiftRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.trnxType = trnxType;
            inValue.Body.inwardSenderBic = inwardSenderBic;
            inValue.Body.swiftField20 = swiftField20;
            inValue.Body.debitValueDate = debitValueDate;
            inValue.Body.creditValueDate = creditValueDate;
            inValue.Body.endpointApp = endpointApp;
            return ((OtpService.ft.ft_genericSoap)(this)).performFundsTransferWithSwiftAsync(inValue);
        }
    }
}
