

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Doubble.DAL.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DoubbleDBEntities : DbContext
{
    public DoubbleDBEntities()
        : base("name=DoubbleDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Branch> Branches { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<DoubbleRequest> DoubbleRequests { get; set; }

    public virtual DbSet<For_Later> For_Later { get; set; }

    public virtual DbSet<ForNonSterling> ForNonSterlings { get; set; }

    public virtual DbSet<ForSterling> ForSterlings { get; set; }

    public virtual DbSet<State_tbl> State_tbl { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Users_tbl> Users_tbl { get; set; }

    public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }

}

}

