//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace imalChannelWS.ibs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ibs.IBSServicesSoap")]
    public interface IBSServicesSoap {
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridge", ReplyAction="*")]
        imalChannelWS.ibs.IBSBridgeResponse IBSBridge(imalChannelWS.ibs.IBSBridgeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridge", ReplyAction="*")]
        System.Threading.Tasks.Task<imalChannelWS.ibs.IBSBridgeResponse> IBSBridgeAsync(imalChannelWS.ibs.IBSBridgeRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridgeNE", ReplyAction="*")]
        imalChannelWS.ibs.IBSBridgeNEResponse IBSBridgeNE(imalChannelWS.ibs.IBSBridgeNERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridgeNE", ReplyAction="*")]
        System.Threading.Tasks.Task<imalChannelWS.ibs.IBSBridgeNEResponse> IBSBridgeNEAsync(imalChannelWS.ibs.IBSBridgeNERequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridgeAppzone", ReplyAction="*")]
        imalChannelWS.ibs.IBSBridgeAppzoneResponse IBSBridgeAppzone(imalChannelWS.ibs.IBSBridgeAppzoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridgeAppzone", ReplyAction="*")]
        System.Threading.Tasks.Task<imalChannelWS.ibs.IBSBridgeAppzoneResponse> IBSBridgeAppzoneAsync(imalChannelWS.ibs.IBSBridgeAppzoneRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridge", Namespace="http://tempuri.org/", Order=0)]
        public imalChannelWS.ibs.IBSBridgeRequestBody Body;
        
        public IBSBridgeRequest() {
        }
        
        public IBSBridgeRequest(imalChannelWS.ibs.IBSBridgeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Appid;
        
        public IBSBridgeRequestBody() {
        }
        
        public IBSBridgeRequestBody(string request, int Appid) {
            this.request = request;
            this.Appid = Appid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridgeResponse", Namespace="http://tempuri.org/", Order=0)]
        public imalChannelWS.ibs.IBSBridgeResponseBody Body;
        
        public IBSBridgeResponse() {
        }
        
        public IBSBridgeResponse(imalChannelWS.ibs.IBSBridgeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IBSBridgeResult;
        
        public IBSBridgeResponseBody() {
        }
        
        public IBSBridgeResponseBody(string IBSBridgeResult) {
            this.IBSBridgeResult = IBSBridgeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeNERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridgeNE", Namespace="http://tempuri.org/", Order=0)]
        public imalChannelWS.ibs.IBSBridgeNERequestBody Body;
        
        public IBSBridgeNERequest() {
        }
        
        public IBSBridgeNERequest(imalChannelWS.ibs.IBSBridgeNERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeNERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Appid;
        
        public IBSBridgeNERequestBody() {
        }
        
        public IBSBridgeNERequestBody(string request, int Appid) {
            this.request = request;
            this.Appid = Appid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeNEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridgeNEResponse", Namespace="http://tempuri.org/", Order=0)]
        public imalChannelWS.ibs.IBSBridgeNEResponseBody Body;
        
        public IBSBridgeNEResponse() {
        }
        
        public IBSBridgeNEResponse(imalChannelWS.ibs.IBSBridgeNEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeNEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IBSBridgeNEResult;
        
        public IBSBridgeNEResponseBody() {
        }
        
        public IBSBridgeNEResponseBody(string IBSBridgeNEResult) {
            this.IBSBridgeNEResult = IBSBridgeNEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeAppzoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridgeAppzone", Namespace="http://tempuri.org/", Order=0)]
        public imalChannelWS.ibs.IBSBridgeAppzoneRequestBody Body;
        
        public IBSBridgeAppzoneRequest() {
        }
        
        public IBSBridgeAppzoneRequest(imalChannelWS.ibs.IBSBridgeAppzoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeAppzoneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Appid;
        
        public IBSBridgeAppzoneRequestBody() {
        }
        
        public IBSBridgeAppzoneRequestBody(string request, int Appid) {
            this.request = request;
            this.Appid = Appid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeAppzoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridgeAppzoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public imalChannelWS.ibs.IBSBridgeAppzoneResponseBody Body;
        
        public IBSBridgeAppzoneResponse() {
        }
        
        public IBSBridgeAppzoneResponse(imalChannelWS.ibs.IBSBridgeAppzoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeAppzoneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IBSBridgeAppzoneResult;
        
        public IBSBridgeAppzoneResponseBody() {
        }
        
        public IBSBridgeAppzoneResponseBody(string IBSBridgeAppzoneResult) {
            this.IBSBridgeAppzoneResult = IBSBridgeAppzoneResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBSServicesSoapChannel : imalChannelWS.ibs.IBSServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BSServicesSoapClient : System.ServiceModel.ClientBase<imalChannelWS.ibs.IBSServicesSoap>, imalChannelWS.ibs.IBSServicesSoap {
        
        public BSServicesSoapClient() {
        }
        
        public BSServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BSServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        imalChannelWS.ibs.IBSBridgeResponse imalChannelWS.ibs.IBSServicesSoap.IBSBridge(imalChannelWS.ibs.IBSBridgeRequest request) {
            return base.Channel.IBSBridge(request);
        }
        
        public string IBSBridge(string request, int Appid) {
            imalChannelWS.ibs.IBSBridgeRequest inValue = new imalChannelWS.ibs.IBSBridgeRequest();
            inValue.Body = new imalChannelWS.ibs.IBSBridgeRequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            imalChannelWS.ibs.IBSBridgeResponse retVal = ((imalChannelWS.ibs.IBSServicesSoap)(this)).IBSBridge(inValue);
            return retVal.Body.IBSBridgeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<imalChannelWS.ibs.IBSBridgeResponse> imalChannelWS.ibs.IBSServicesSoap.IBSBridgeAsync(imalChannelWS.ibs.IBSBridgeRequest request) {
            return base.Channel.IBSBridgeAsync(request);
        }
        
        public System.Threading.Tasks.Task<imalChannelWS.ibs.IBSBridgeResponse> IBSBridgeAsync(string request, int Appid) {
            imalChannelWS.ibs.IBSBridgeRequest inValue = new imalChannelWS.ibs.IBSBridgeRequest();
            inValue.Body = new imalChannelWS.ibs.IBSBridgeRequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            return ((imalChannelWS.ibs.IBSServicesSoap)(this)).IBSBridgeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        imalChannelWS.ibs.IBSBridgeNEResponse imalChannelWS.ibs.IBSServicesSoap.IBSBridgeNE(imalChannelWS.ibs.IBSBridgeNERequest request) {
            return base.Channel.IBSBridgeNE(request);
        }
        
        public string IBSBridgeNE(string request, int Appid) {
            imalChannelWS.ibs.IBSBridgeNERequest inValue = new imalChannelWS.ibs.IBSBridgeNERequest();
            inValue.Body = new imalChannelWS.ibs.IBSBridgeNERequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            imalChannelWS.ibs.IBSBridgeNEResponse retVal = ((imalChannelWS.ibs.IBSServicesSoap)(this)).IBSBridgeNE(inValue);
            return retVal.Body.IBSBridgeNEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<imalChannelWS.ibs.IBSBridgeNEResponse> imalChannelWS.ibs.IBSServicesSoap.IBSBridgeNEAsync(imalChannelWS.ibs.IBSBridgeNERequest request) {
            return base.Channel.IBSBridgeNEAsync(request);
        }
        
        public System.Threading.Tasks.Task<imalChannelWS.ibs.IBSBridgeNEResponse> IBSBridgeNEAsync(string request, int Appid) {
            imalChannelWS.ibs.IBSBridgeNERequest inValue = new imalChannelWS.ibs.IBSBridgeNERequest();
            inValue.Body = new imalChannelWS.ibs.IBSBridgeNERequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            return ((imalChannelWS.ibs.IBSServicesSoap)(this)).IBSBridgeNEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        imalChannelWS.ibs.IBSBridgeAppzoneResponse imalChannelWS.ibs.IBSServicesSoap.IBSBridgeAppzone(imalChannelWS.ibs.IBSBridgeAppzoneRequest request) {
            return base.Channel.IBSBridgeAppzone(request);
        }
        
        public string IBSBridgeAppzone(string request, int Appid) {
            imalChannelWS.ibs.IBSBridgeAppzoneRequest inValue = new imalChannelWS.ibs.IBSBridgeAppzoneRequest();
            inValue.Body = new imalChannelWS.ibs.IBSBridgeAppzoneRequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            imalChannelWS.ibs.IBSBridgeAppzoneResponse retVal = ((imalChannelWS.ibs.IBSServicesSoap)(this)).IBSBridgeAppzone(inValue);
            return retVal.Body.IBSBridgeAppzoneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<imalChannelWS.ibs.IBSBridgeAppzoneResponse> imalChannelWS.ibs.IBSServicesSoap.IBSBridgeAppzoneAsync(imalChannelWS.ibs.IBSBridgeAppzoneRequest request) {
            return base.Channel.IBSBridgeAppzoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<imalChannelWS.ibs.IBSBridgeAppzoneResponse> IBSBridgeAppzoneAsync(string request, int Appid) {
            imalChannelWS.ibs.IBSBridgeAppzoneRequest inValue = new imalChannelWS.ibs.IBSBridgeAppzoneRequest();
            inValue.Body = new imalChannelWS.ibs.IBSBridgeAppzoneRequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            return ((imalChannelWS.ibs.IBSServicesSoap)(this)).IBSBridgeAppzoneAsync(inValue);
        }
    }
}
