//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVNAcctCreation.BVN {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BVN.ProcessWebBVNSoap")]
    public interface ProcessWebBVNSoap {
        
        // CODEGEN: Generating message contract since element name msg from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcessWeb", ReplyAction="*")]
        BVNAcctCreation.BVN.ProcessWebResponse ProcessWeb(BVNAcctCreation.BVN.ProcessWebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcessWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<BVNAcctCreation.BVN.ProcessWebResponse> ProcessWebAsync(BVNAcctCreation.BVN.ProcessWebRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessWebRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessWeb", Namespace="http://tempuri.org/", Order=0)]
        public BVNAcctCreation.BVN.ProcessWebRequestBody Body;
        
        public ProcessWebRequest() {
        }
        
        public ProcessWebRequest(BVNAcctCreation.BVN.ProcessWebRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessWebRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Appid;
        
        public ProcessWebRequestBody() {
        }
        
        public ProcessWebRequestBody(string msg, int Appid) {
            this.msg = msg;
            this.Appid = Appid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessWebResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessWebResponse", Namespace="http://tempuri.org/", Order=0)]
        public BVNAcctCreation.BVN.ProcessWebResponseBody Body;
        
        public ProcessWebResponse() {
        }
        
        public ProcessWebResponse(BVNAcctCreation.BVN.ProcessWebResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessWebResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessWebResult;
        
        public ProcessWebResponseBody() {
        }
        
        public ProcessWebResponseBody(string ProcessWebResult) {
            this.ProcessWebResult = ProcessWebResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProcessWebBVNSoapChannel : BVNAcctCreation.BVN.ProcessWebBVNSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessWebBVNSoapClient : System.ServiceModel.ClientBase<BVNAcctCreation.BVN.ProcessWebBVNSoap>, BVNAcctCreation.BVN.ProcessWebBVNSoap {
        
        public ProcessWebBVNSoapClient() {
        }
        
        public ProcessWebBVNSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessWebBVNSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessWebBVNSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessWebBVNSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BVNAcctCreation.BVN.ProcessWebResponse BVNAcctCreation.BVN.ProcessWebBVNSoap.ProcessWeb(BVNAcctCreation.BVN.ProcessWebRequest request) {
            return base.Channel.ProcessWeb(request);
        }
        
        public string ProcessWeb(string msg, int Appid) {
            BVNAcctCreation.BVN.ProcessWebRequest inValue = new BVNAcctCreation.BVN.ProcessWebRequest();
            inValue.Body = new BVNAcctCreation.BVN.ProcessWebRequestBody();
            inValue.Body.msg = msg;
            inValue.Body.Appid = Appid;
            BVNAcctCreation.BVN.ProcessWebResponse retVal = ((BVNAcctCreation.BVN.ProcessWebBVNSoap)(this)).ProcessWeb(inValue);
            return retVal.Body.ProcessWebResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BVNAcctCreation.BVN.ProcessWebResponse> BVNAcctCreation.BVN.ProcessWebBVNSoap.ProcessWebAsync(BVNAcctCreation.BVN.ProcessWebRequest request) {
            return base.Channel.ProcessWebAsync(request);
        }
        
        public System.Threading.Tasks.Task<BVNAcctCreation.BVN.ProcessWebResponse> ProcessWebAsync(string msg, int Appid) {
            BVNAcctCreation.BVN.ProcessWebRequest inValue = new BVNAcctCreation.BVN.ProcessWebRequest();
            inValue.Body = new BVNAcctCreation.BVN.ProcessWebRequestBody();
            inValue.Body.msg = msg;
            inValue.Body.Appid = Appid;
            return ((BVNAcctCreation.BVN.ProcessWebBVNSoap)(this)).ProcessWebAsync(inValue);
        }
    }
}
